
# Tg设置，具体获取方式见 
# https://tgymw.net/telegram-%e7%94%b5%e6%8a%a5%e5%bc%80%e5%8f%91%e8%80%85api_id-%e5%92%8c-api_hash-%e7%94%b3%e8%af%b7%e6%95%99%e7%a8%8b
[telegram]
api_id = 
api_hash = 
## session_name 默认即可
session_name = data/tg_music_cli

# 代理设置
[proxy]
## false为关闭，true为开启
enable = false
## 支持http(s)/socks
type = socks5
hostname = 127.0.0.1
port = 1080
username = 
password = 

# 下载路径设置
[设置]
## 该路径为映射到容器内的路径，非物理机路径
download_directory = /music
## 未下载完成的歌曲是否开启缓存后缀，解决mustag整理掉未完成的歌曲问题
use_tmp_suffix = true

# AI设置，通过ai对歌曲进行分类
[ai]
## false为关闭，true为开启
enable = true
## 兼容openai、gemini，字段可选为openai或gemini
provider = openai
## 可以使用硅基流动平台，走邀请每人得14元试用，https://cloud.siliconflow.cn/i/3rjsr2yL
base_url = https://api.siliconflow.cn
api_key = 
model = 
## ai最大试错次数
max_retries = 3
## 分类标签
categories = 华语,日韩,欧美,纯音乐,未知

# 企业微信自建应用设置
[wecom]
## false为关闭，true为开启
enabled = true
## 企业ID
corp_id = 
## 应用AgentID
agent_id =
## 应用Secret 
secret = 
## Token
token = 
## EncodingAESKey
encoding_aes_key = 
## 微信消息的转发代理地址
api_base = 
## 企业微信的API接收消息地址，企业微信后台在“API接收消息”设置页面，将URL设置为 http://x.x.x.x:18000/wecom/callback
callback_host = 0.0.0.0
callback_port = 18000
